; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Volume slides are used, you must set FAMISTUDIO_USE_VOLUME_SLIDES = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_mine_clearance=music_data_mine_clearance
.endif

music_data_mine_clearance:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_mine_clearance
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env5,@env7,@env10,@env0 ; 00 : Bass
	.word @env5,@env16,@env10,@env0 ; 01 : Bass Slap
	.word @env13,@env14,@env10,@env0 ; 02 : Drum C4
	.word @env8,@env4,@env10,@env0 ; 03 : Snare C4
	.word @env2,@env3,@env10,@env0 ; 04 : CH F3
	.word @env15,@env7,@env11,@env0 ; 05 : Strings
	.word @env1,@env9,@env10,@env0 ; 06 : OH F3
	.word @env6,@env12,@env10,@env0 ; 07 : Crash B3

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$04,$c9,$c0,$00,$04
@env2:
	.byte $00,$cf,$02,$c8,$c0,$00,$04
@env3:
	.byte $c0,$c3,$c5,$00,$02
@env4:
	.byte $c0,$c3,$c6,$c7,$00,$03
@env5:
	.byte $00,$cf,$7f,$00,$02
@env6:
	.byte $00,$cf,$cd,$cc,$c8,$c5,$c4,$c1,$c0,$00,$08
@env7:
	.byte $c0,$7f,$00,$01
@env8:
	.byte $00,$cf,$05,$c8,$c0,$00,$04
@env9:
	.byte $c0,$c1,$c2,$c3,$c4,$c5,$00,$05
@env10:
	.byte $7f,$00,$00
@env11:
	.byte $c2,$7f,$00,$00
@env12:
	.byte $c0,$c1,$c4,$c8,$ca,$00,$04
@env13:
	.byte $00,$cf,$cf,$ce,$c7,$c0,$00,$05
@env14:
	.byte $c0,$bf,$00,$01
@env15:
	.byte $00,$cb,$cc,$ce,$cf,$ce,$ce,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$c9,$c9,$c8,$c5,$00,$11
@env16:
	.byte $cc,$c0,$00,$01

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $77, $eb, $8a
@song0ref4:
	.byte $27, $ff, $b1, $48, $00, $e9, $29, $ff, $b1, $48, $00, $e9, $2c, $ff, $b1, $48, $00, $e9, $2e, $e9, $51, $fd, $20, $c7
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $72, $00, $e9
	.byte $41, $10
	.word @song0ref4
	.byte $ff, $9f, $00, $8f, $42
	.word @song0ch0loop
@song0ch1:
	.byte $77, $c7, $8a
@song0ref48:
	.byte $24, $ff, $d5, $00, $c5, $27, $ff, $d5, $00, $c5, $29, $ff, $d5, $00, $c5, $2c, $ff, $8d, $51, $fd, $20, $c7
@song0ch1loop:
	.byte $72, $00, $c5
	.byte $41, $11
	.word @song0ref48
	.byte $c3, $00, $8f, $42
	.word @song0ch1loop
@song0ch2:
@song0ref83:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
@song0ch2loop:
	.byte $80, $14, $a1, $82, $20
@song0ref101:
	.byte $8f, $00, $8f, $80, $16, $a1, $82, $22, $8f, $00, $8f, $80, $1b, $a1, $82, $24, $8f, $00, $8f, $80, $1d, $a1, $82, $27
	.byte $41, $12
	.word @song0ref101
@song0ref128:
	.byte $8f, $00, $8f, $80, $20, $a1, $82, $29, $8f, $00, $8f, $80, $1b, $a1, $82, $27, $8f, $00, $8f, $80, $1d, $a1, $82, $29
	.byte $8f, $00, $8f, $80, $20, $a1, $82, $2c, $8f, $00, $8f, $80, $24, $a1, $82, $2e, $8f, $00, $8f, $80, $1d, $a1, $82, $27
	.byte $41, $09
	.word @song0ref128
	.byte $80, $22, $a1, $82, $2c, $8f, $00, $8f, $80, $27, $a1, $82, $2e, $8f, $00, $8f, $42
	.word @song0ch2loop
@song0ch3:
	.byte $41, $0a
	.word @song0ref83
	.byte $fb, $8e, $24, $8f, $24, $8f
@song0ch3loop:
	.byte $84, $25, $a1
@song0ref211:
	.byte $8c
@song0ref212:
	.byte $1e, $8f, $00, $8f, $86, $25, $a1, $88, $1e, $8f, $00, $8f
@song0ref224:
	.byte $1e, $8f, $00, $8f, $84, $25, $a1
@song0ref231:
	.byte $86, $25, $a1, $88, $1e, $8f, $00, $8f, $84, $25, $8f, $25, $8f
	.byte $41, $0a
	.word @song0ref211
	.byte $84, $25, $8f, $25, $8f, $00, $8f, $25, $8f
	.byte $41, $08
	.word @song0ref231
@song0ref259:
	.byte $00, $8f, $25, $8f, $25, $8f, $86, $25, $a1, $88, $1e, $8f, $00, $8f, $84, $25, $a1, $88
	.byte $41, $0a
	.word @song0ref212
	.byte $84, $25, $8f
	.byte $41, $08
	.word @song0ref259
	.byte $84, $25, $8f, $00, $8f, $88
	.byte $41, $08
	.word @song0ref224
	.byte $8c, $1e, $8f, $00, $8f, $42
	.word @song0ch3loop
@song0ch4:
	.byte $41, $0c
	.word @song0ref83
@song0ch4loop:
	.byte $41, $0c
	.word @song0ref83
	.byte $42
	.word @song0ch4loop
@song0ch5:
	.byte $a3, $8a
@song0ref315:
	.byte $22, $ff, $f9, $00, $a1, $24, $ff, $f9, $00, $a1, $27, $ff, $f9, $00, $a1, $29, $ff, $b1, $51, $fd, $90, $c7
@song0ch5loop:
	.byte $79, $00, $a1
	.byte $41, $11
	.word @song0ref315
	.byte $e7, $00, $8f, $42
	.word @song0ch5loop
@song0ch6:
	.byte $8a
@song0ref351:
	.byte $20, $ff, $ff, $9d, $22, $ff, $ff, $9d, $24, $ff, $ff, $9d, $25, $ff, $d5, $51, $fd, $90, $c7
@song0ch6loop:
	.byte $79
	.byte $41, $0e
	.word @song0ref351
	.byte $ff, $9d, $42
	.word @song0ch6loop
